# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0"
    hooks:
      # backend
      - id: poetry-check
        args: ["-C", "./backend"]
        language_version: python3.11
      - id: poetry-lock
        args: ["-C", "./backend"]
        language_version: python3.11
      - id: poetry-export
        args:
          [
            "-C",
            "./backend",
            "-f",
            "requirements.txt",
            "-o",
            "./backend/requirements.txt",
          ]
        language_version: python3.11
