apiVersion: v1
kind: ConfigMap
metadata:
  name: connor-ai-config
data:
  LANGCHAIN_TRACING_V2: "{{ .Values.backend.integrations.langchain.tracingV2 }}"
  LANGCHAIN_ENDPOINT: "{{ .Values.backend.integrations.langchain.endpoint }}"
  CALENDLY_ACCOUNT: "{{ .Values.backend.calendly.account }}"
  DB_PORT: "{{ .Values.backend.database.port }}"
  ALLOWED_ORIGINS: "{{ .Values.backend.origins.allowedOrigins }}"
  STORAGE_TYPE: "{{ .Values.backend.storage.storageType }}"
  BASE_DIR: "{{ .Values.backend.storage.baseDir }}"
