apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.backend.name}}-ingress
  annotations:
    networking.gke.io/managed-certificates: {{.Values.backend.ingress.host}}-certificate
    cloud.google.com/backend-config: '{"default": "backend-health"}'
    kubernetes.io/ingress.class: "gce" 
spec:
  rules:
    - host: {{.Values.backend.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.backend.name}}
                port:
                  number: {{.Values.backend.service.port}}