apiVersion: v1
kind: Secret
metadata:
  name: connor-ai-secrets
type: Opaque
data:
  OPENAI_API_KEY: {{.Values.backend.secrets.openai.apiKey | b64enc}}
  TAVILY_API_KEY: {{.Values.backend.secrets.tavily.apiKey | b64enc}}
  LANGCHAIN_API_KEY: {{.Values.backend.secrets.langchain.apiKey | b64enc}}
  GITHUB_TOKEN: {{.Values.backend.secrets.github.token | b64enc}}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
    {{.Values.backend.secrets.clerk.publishableKey | b64enc}}
  CLERK_SECRET_KEY: {{.Values.backend.secrets.clerk.secretKey | b64enc}}
  DB_PASSWORD: {{.Values.backend.secrets.database.password | b64enc}}
  DB_DIRECT_URL: {{.Values.backend.secrets.database.directUrl | b64enc}}
  DB_USER: {{.Values.backend.secrets.database.user | b64enc}}
  DB_HOST: {{.Values.backend.secrets.database.host | b64enc}}
