apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.name}}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8000":"backend-health"}}'
    networking.gke.io/v1beta1.FrontendConfig: "https-redirect"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.backend.service.port}}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{.Values.backend.name}}
