apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.name}}
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.backend.service.port}}
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{.Values.backend.name}}
