apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.frontend.name}}
  annotations:
    networking.gke.io/managed-certificates: {{.Values.frontend.ingress.host}}-certificate
spec:
  rules:
    - host: {{.Values.frontend.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.frontend.name}}
                port:
                  number: {{.Values.frontend.service.port}}