apiVersion: v1
kind: Secret
metadata:
  name: connor-frontend-secrets
type: Opaque
data:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
    {{.Values.frontend.secrets.clerk.publishableKey | b64enc}}
  CLERK_SECRET_KEY: {{.Values.frontend.secrets.clerk.secretKey | b64enc}}
