apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-traffic
spec:
  podSelector:
    matchLabels:
      app: connor-frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 130.211.0.0/22 # Google LB range
        - ipBlock:
            cidr: 35.191.0.0/16 # Google LB range
      ports:
        - protocol: TCP
          port: 3000

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-traffic
spec:
  podSelector:
    matchLabels:
      app: connor-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 130.211.0.0/22 # Google LB range
        - ipBlock:
            cidr: 35.191.0.0/16 # Google LB range
        - podSelector:
            matchLabels:
              app: connor-frontend
      ports:
        - protocol: TCP
          port: 3000
