apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-health
spec:
  healthCheck:
    checkIntervalSec: 300
    timeoutSec: 10
    type: HTTP
    requestPath: /docs
    port: 8000
    initialDelaySeconds: 40
    periodSeconds: 10
    failureThreshold: 3

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-health
spec:
  healthCheck:
    checkIntervalSec: 300
    timeoutSec: 10
    type: HTTP
    requestPath: /sign-in
    port: 3000
    initialDelaySeconds: 40
    periodSeconds: 10
    failureThreshold: 3
# TODO replace with a health check endpoint

