apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccount.name}}
  namespace: {{.Values.serviceAccount.namespace}}
  annotations:
    iam.gke.io/gcp-service-account: "gcs-access-sa@{{ .Values.projectId }}.iam.gserviceaccount.com"
