apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccount.name}}
  namespace: {{.Values.serviceAccount.namespace}}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: myapp
    meta.helm.sh/release-namespace: default
    iam.gke.io/gcp-service-account: "gcs-access-sa@{{ .Values.projectId }}.iam.gserviceaccount.com"
