frontend:
  name: connor-frontend
  replicas: 1
  service:
    port: 3000
  ingress:
    enabled: true
  env:
    INTERNAL_CONNOR_BACKEND_URL: http://connor-backend.default.svc.cluster.local:8000
backend:
  name: connor-backend
  replicas: 1
  service:
    port: 8000
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    NODE_ENV: production
  calendly:
    account: connor-haines
  integrations:
    langchain:
      tracingV2: true
      endpoint: https://api.smith.langchain.com
