backend:
  image:
    tag: latest
  ingress:
    enabled: true
    host: api.connor-haines.com
  origins:
    allowedOrigins: "https://connor-haines.com,http://connor-frontend.default.svc.cluster.local"
  database:
    port: 6543
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"

frontend:
  image:
    tag: latest
  env:
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
    NEXT_PUBLIC_BACKEND_URL: https://api.connor-haines.com
  ingress:
    enabled: true
    host: connor-haines.com
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
