backend:
  storage:
    storageType: local
    baseDir: "system_prompts"
  image:
    repository: connor-backend
    tag: latest
  database:
    port: 6543
  ingress:
    host: localhost
  origins:
    allowedOrigins: "http://localhost,http://localhost:3000,http://host.docker.internal:3000,http://connor-frontend:3000,https://connor-haines.com"
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

frontend:
  image:
    repository: connor-frontend
    tag: latest
  env:
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
    NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
  ingress:
    host: localhost
  resources:
    limits:
      cpu: "1500m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
