backend:
  image:
    tag: latest
  ingress:
    enabled: true
    host: api.connor-haines.com
  database:
    port: 6543

frontend:
  image:
    tag: latest
  env:
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
    NEXT_PUBLIC_BACKEND_URL: https://api.connor-haines.com
  ingress:
    enabled: true
    host: connor-haines.com
